all:
  children:
    cafwfrontend:
      hosts:
        192.168.0.245:
          ansible_ssh_private_key_file: caadmin
          ansible_ssh_user: 'caadmin'
    cafwbackend:
      hosts:
        192.168.0.246:
          ansible_ssh_private_key_file: caadmin
          ansible_ssh_user: 'caadmin'
    caserver02:
      hosts:
        192.168.0.247:
          ansible_ssh_private_key_file: caadmin
          ansible_ssh_user: 'caadmin'
    caserver01:
      hosts:
        192.168.0.248:
          ansible_ssh_private_key_file: caadmin
          ansible_ssh_user: 'caadmin'